image: docker:latest

services:
  - docker:dind

stages:
  - build

build:
  only:
    - tags
  stage: build
  script:
    - echo $CI_COMMIT_TAG
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    # - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME" .
    - docker build --pull -t $CI_REGISTRY_IMAGE .
    - docker tag $CI_REGISTRY_IMAGE $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    # - docker push "$CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME"
    - docker push $CI_REGISTRY_IMAGE
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG